###
GET http://localhost:3000/api/commerces?sortByCIF=asc HTTP/1.1

###
GET http://localhost:3000/api/commerces/sortByCIF='asc' HTTP/1.1

###
GET http://localhost:3000/api/commerces/B12345678 HTTP/1.1

###
POST http://localhost:3000/api/commerces HTTP/1.1
Content-Type: application/json

{
    "name": "Commerce 1",
    "cif": "A12345678",
    "address": "Address 1",
    "email": "test@mail.com",
    "contact": "661234567",
    "siteId": 1 
}

###
POST http://localhost:3000/api/commerces HTTP/1.1
Content-Type: application/json

{
    "name": "Commerce 2",
    "cif": "B12345678",
    "address": "Address 2",
    "email": "2@mail.com",
    "contact": "883456789",
    "siteId": 2 
}

###
POST http://localhost:3000/api/commerces HTTP/1.1
Content-Type: application/json

{
    "name": "Commerce 3",
    "cif": "C12345678",
    "address": "Address 3",
    "email": "3@mail.com",
    "contact": "883456789",
    "siteId": 3 
}

###
PUT http://localhost:3000/api/commerces/C12345678 HTTP/1.1
Content-Type: application/json

{
    "name": "Updated Commerce 3",
    "cif": "B12345678",
    "address": "Address 2",
    "email": "2@mail.com",
    "contact": "883456789",
    "siteId": 2
}

###
DELETE http://localhost:3000/api/commerces/C12345678?logical=true HTTP/1.1

###
DELETE http://localhost:3000/api/commerces/C12345678 HTTP/1.1


